name: Build, Test, and Execute C Program

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libjansson-dev

    - name: Compile C Program
      run: gcc -o suricata-notify suricata-notify.c -ljansson

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: suricata-notify
        path: suricata-notify
        retention-days: 30

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: suricata-notify
        path: ./

    - name: List Downloaded Files
      run: ls -la

    - name: Check File Type
      run: file ./suricata-notify

    - name: Make Executable
      run: chmod +x ./suricata-notify

    - name: Verify Executable Permissions
      run: ls -l ./suricata-notify

    - name: Print Working Directory
      run: pwd

    - name: List Directory Contents
      run: ls -la

    - name: Execute Binary
      run: ./suricata-notify
