name: Build, Test, and Execute C Program with CMake

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Essentials and Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libjansson-dev cmake

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: suricata-notify-${{env.BUILD_TYPE}}
        path: build/suricata-notify
        retention-days: 30  # Retain the artifact for 30 days

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: suricata-notify-${{env.BUILD_TYPE}}
        path: build/

    - name: List Downloaded Files
      run: ls -la build/

    - name: Make Executable
      run: chmod +x build/suricata-notify

    - name: Execute Binary
      run: ./build/suricata-notify
