name: Desktop Notification Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xfce4-notifyd x11-apps x11-utils strace

      - name: Create and Run Notification Test Script
        run:  export DISPLAY=:99 && sudo xvfb -ac :99 "-screen 0 1024x768x24" > /dev/null 2>&1 && xfce4-notifyd "Test Notification" "This is a test message.";
